#!/bin/sh
### BEGIN INIT INFO
# Provides:          device
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Device 
### END INIT INFO

DAEMON_PATH=/usr/sbin/device
DAEMON_NAME=`basename $DAEMON_PATH`
DEVICE_MGR=""
DEVICE_USR=""

test -x $DAEMON_PATH || exit 0

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

RETVAL=0
device_mgr_cfg="/etc/default/device_mgr.cfg"

get_device_mgr() {
    for arg in `cat /proc/cmdline` ; do
      if [ "${arg##device_mgr=}" != "${arg}" ]; then
	DEVICE_MGR=${arg##device_mgr=}
	return
      fi
      if [ "${arg##device_mgr_cfg=}" != "${arg}" ]; then
        device_mgr_cfg=${arg##device_mgr_cfg=}
	break
      fi
    done
    if [ "device_mgr_cfg" != "" ]; then
	DEVICE_MGR=file:${device_mgr_cfg}
    fi
}

set_hac_user() {
    
    if [ -e /etc/default/hacUser.cfg ]; then
        DEVICE_USR=`cat /etc/default/hacUser.cfg`
    fi
}

case "$1" in
    start)
        echo -n "Starting $DAEMON_NAME: "
	get_device_mgr
        set_hac_user
	if [ "$DEVICE_MGR" = "" ]; then
	    echo "Missing Device Mgr URL, which is required for $DAEMON_NAME to run"
	    echo "SKIP"
	    exit 0
	else
            if [ "$DEVICE_USR" = "" ]; then
                echo "Starting hac.service as root"
	        $DAEMON_PATH -d $DEVICE_MGR
            else
               echo "Starting hac.service as " $DEVICE_USR
               su -c "$DAEMON_PATH -d $DEVICE_MGR" $DEVICE_USR
            fi
	    RETVAL=$?
	    if [ $RETVAL -eq 0 ] ; then
		echo "OK"
		touch /var/lock/subsys/$DAEMON_NAME
	    else
		echo "FAIL"
		exit 1
	    fi
	fi
        ;;

    stop)
        echo -n "Stopping $DAEMON_NAME: "
        count=0
	killall $DAEMON_PATH
        rm -f /var/lock/subsys/$DAEMON_NAME
	ps -ef |grep $DAEMON_PATH > /dev/null 2>/dev/null
        if [ $? = 0 ] ; then
            echo "OK"
        else
            echo "FAIL"
        fi
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        status $DAEMON_NAME
        RETVAL=$?
        ;;

    condrestart)
        [ -f /var/lock/subsys/$DAEMON_NAME ] && $0 restart
        ;;

    *)
        echo "usage: $0 { start | stop | status | restart | condrestart | status }"
        ;;
esac

exit $RETVAL

